### ISSUE TITLE
RESTConnector loses header values.

### ISSUE THREAD

**Issue by fshafique** [bonitasoft/bonita-connector-rest#30]
For example, Bonitasoft BPM server returns this from a login request:
```HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Set-Cookie: bonita.tenant=1
Set-Cookie: JSESSIONID=FDFB2C8CD28C6C13222FE49E2C1DC32F; Path=/bonita; HttpOnly
Set-Cookie: X-Bonita-API-Token=6c4698ce-3e25-407d-8c40-cdab15a63aad; Path=/
Content-Length: 0
Date: Thu, 26 Oct 2017 10:25:55 GMT
```

Here, the "Set-Cookie" header is repeated 3 times. The RESTConnector.java file will convert Header[] to a Map, but one key maps to one value, and so only one "Set-Cookie" header will remain.

The problem code is here (below). My recommendation would be to return an array of values, if there are multiple.
https://github.com/bonitasoft/bonita-connector-rest/blob/422d12c32e780866cc445c6e3d9cb50bc3fbaf0a/src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java#L436-L444

**Comment by rbioteau** [comment]
Fixed integrated in Bonita 7.8
