### ISSUE TITLE
I can't build the project at it's root level as said in the Readme.md

### ISSUE THREAD

**Issue by eddysen** [bonitasoft/bonita-connector-rest#31]
Hello please can'i have your support on building the project ? Here is the process i followed.
---------------------------
 $ git clone https://github.com/bonitasoft/bonita-connector-rest.git
 $ cd bonita-connector-rest/
 $ mvn clean verify
 ---------------------------

But i'm facing this issue : 

----------------------------
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.bonitasoft.connectors:bonita-connector-rest:1.0.5-SNAPSHOT: Failure to find org.bonitasoft.connectors:bonita-connectors:pom:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 4, column 13

---------------------------------
What i'm doing wrong ?

**Comment by jALEXj** [comment]
Hi, same problem here:

```
mvn clean verify

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.bonitasoft.connectors:bonita-connector-rest:1.0.4: Failure to find org.bonitasoft.connectors:bonita-connectors:pom:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 4, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.bonitasoft.connectors:bonita-connector-rest:1.0.4 (D:\Users\.....\Downloads\bonita-connector-rest-1.0.4\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.bonitasoft.connectors:bonita-connector-rest:1.0.4: Failure to find org.bonitasoft.connectors:bonita-connectors:pom:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 4, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by tbouffard** [comment]
Hi there,
the bonita-connector parent pom is not available on Maven Central, you have to install it manually.

Go to https://github.com/bonitasoft/bonita-connectors and do what is written in the README
I will propose an improvement in the Readme to explain that

**Comment by rbioteau** [comment]
Hi  @jALEXj, the parent dependency has been pushed on the public repositories.
