### ISSUE TITLE
If HTTP code is not OK, outputs are not filled (so the process cannot access error message)

### ISSUE THREAD

**Issue by vsapouno** [bonitasoft/bonita-connector-rest#32]
We use the REST connector configured to "Ignore error and continue process" so the process can check the HTTP response code itself, get the error response body, and report it gracefully to the user.

However, the connector does not fill any outputs if the connector sees the HTTP error code is not 2xx or 3xx, as you can see in `RESTConnector.execute()`:

```
            if (!statusSuccessful(statusCode)) {
                throw new ConnectorException(
                        String.format("%s response status is not successful: %s - %s", request, statusCode, httpResponse.getStatusLine().getReasonPhrase()));
            }
            setOutputs(httpResponse, request);
```

The fix would be to move `setOutputs()` before the exception is thrown (above `if`), so outputs are always set for the process to analyze.

**Comment by rbioteau** [comment]
Hi,
setting the output before the Exception is thrown will not help you in this use case.
The exception will prevent output operations to execute anyway.

A proper way would be to have an option to not throw that exception if it is the expected behavior and handle the error process side using the status_code output value.

**Comment by dantebarba** [comment]
Same here, how can we handle these cases?. It's impossible to handle error events correctly without the correct status code returned by the API Call.

**Comment by rbioteau** [comment]
In the current state you may use the 'throw error message' on failure feature on a connector.
However you won't have the proper http status.
We might consider adding a new parameter to support this behavior (like 'Fail on error status') . It will mean the task/connector will not be put on error and the process design will have to implement error management.

**Comment by dantebarba** [comment]
> In the current state you may use the 'throw error message' on failure feature on a connector.
> However you won't have the proper http status.
> We might consider adding a new parameter to support this behavior (like 'Fail on error status') . It will mean the task/connector will not be put on error and the process design will have to implement error management.

I forked the project and patched the exception, then generated the jar files and imported the implementation into bonita. The only issue that I'm seeing is that bonita engine randomly picks up the old implementation.

**Comment by tbouffard** [comment]
@dantebarba can you please provide more details about the `bonita engine randomly picks up the old implementation.`?
how did you import the implementation? on which bonita version? studio or live distribution? ....

**Comment by rbioteau** [comment]
@dantebarba if you go with your own implementation, don't forget to update the implementation version in *.impl files.

**Comment by dantebarba** [comment]
Solved

1- Rebuild the connector, upgrading the pom version to 1.0.7.
2- Replaced all connectors that were attached to the old impl, with the recently added ones.
3- Went to 'Manage Jars' and deleted the old impl jars (1.0.6 and 1.0.4)

Yes, the new impl was selected on the new connector version, but Bonita was
randomly picking up different classes from classloader. Now its working
fine.

Bonita studio Community, version 7.7.4

Thank you

**Comment by rbioteau** [comment]
Fix by https://github.com/bonitasoft/bonita-connector-rest/pull/46
